version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:10"
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-docs-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v1-docs-deps-{{ checksum "package.json" }}
            - v1-docs-deps
      - run:
          name: Install dependencies
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn install
            fi
      - save_cache:
          key: v1-docs-deps-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
      - run:
          name: Setup git configuration
          command: |
            git config --global user.email "bot@kcnt.info"
            git config --global user.name "kcnt-bot"
      - run:
          name: Release new version
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn release || true
            fi
      - run:
          name: Build the website
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy
            fi
